<?php
/**
 * tour-itinerary-pdf.php — Download PDF itinerary tour (publik, tanpa login)
 * GET /tour-itinerary-pdf.php?slug=xxx
 */
require_once 'includes/config.php';
require_once 'includes/db.php';
require_once 'includes/functions.php';
require_once 'includes/fpdf.php';

$slug = trim($_GET['slug'] ?? '');
if (!$slug) { http_response_code(404); die('Slug required.'); }

$stmt = db()->prepare("SELECT * FROM tours WHERE slug = ? AND is_active = 1 LIMIT 1");
$stmt->execute([$slug]);
$tour = $stmt->fetch();
if (!$tour) { http_response_code(404); die('Tour not found.'); }

$itineraries = getItineraries($tour['id']);
$cover = getTourImage($tour, 'large');

// PDF Class
class TourPDF extends FPDF
{
    public function Header()
    {
        // Header bar
        $this->SetFillColor(0, 100, 210);
        $this->Rect(0, 0, 210, 12, 'F');
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 9);
        $this->SetXY(10, 3);
        $this->Cell(0, 6, 'TourAndTravel — Tour Itinerary', 0, 0, 'C');
        $this->Ln(16);
    }

    public function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(150, 150, 150);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }
}

$pdf = new TourPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 20);
$pdf->AddPage();

// === Cover image ===
if ($cover && $cover !== 'assets/img/placeholder.svg' && is_file($cover)) {
    // Place image at top with aspect ratio
    $pdf->Image($cover, 10, $pdf->GetY(), 190, 0, '');
    $pdf->Ln(95);
} else {
    $pdf->Ln(10);
}

// === Title ===
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(26, 26, 46);
$pdf->MultiCell(0, 10, $tour['title'], 0, 'L');
$pdf->Ln(2);

// === Meta info ===
$pdf->SetFont('Helvetica', '', 10);
$pdf->SetTextColor(90, 97, 120);
$meta = [];
if ($tour['category']) $meta[] = 'Category: ' . $tour['category'];
if (!empty($tour['duration'])) $meta[] = 'Duration: ' . $tour['duration'];
if ($tour['max_participants']) $meta[] = 'Max: ' . $tour['max_participants'] . ' pax';
$price = 'Price: ' . formatCurrencySpan($tour['price'], $tour['price_currency'] ?? 'IDR');
$meta[] = strip_tags($price);
$pdf->Cell(0, 6, implode('  |  ', $meta), 0, 1, 'L');
$pdf->Ln(6);

// Separator
$pdf->SetDrawColor(0, 100, 210);
$pdf->SetLineWidth(0.5);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(8);

// === Itinerary Days ===
if (empty($itineraries)) {
    $pdf->SetFont('Helvetica', '', 11);
    $pdf->SetTextColor(150, 150, 150);
    $pdf->Cell(0, 10, 'No itinerary details available.', 0, 1, 'C');
}

foreach ($itineraries as $it) {
    // Day header
    $startY = $pdf->GetY();
    $pdf->SetFillColor(240, 245, 250);
    $pdf->SetFont('Helvetica', 'B', 12);
    $pdf->SetTextColor(0, 100, 210);
    $pdf->Rect(10, $startY, 190, 8, 'F');
    $pdf->SetXY(14, $startY + 1);
    $pdf->Cell(0, 6, 'Day ' . $it['day_number'] . ' — ' . $it['title'], 0, 1, 'L');
    $pdf->Ln(3);

    // Description
    if ($it['description']) {
        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(60, 60, 80);
        $pdf->SetX(14);
        $pdf->MultiCell(180, 5.5, strip_tags($it['description']), 0, 'L');
        $pdf->Ln(1);
    }

    // Badges
    $badgeStart = $pdf->GetY();
    if ($it['meals']) {
        $pdf->SetFont('Helvetica', '', 9);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFillColor(40, 167, 69);
        $pdf->SetXY(14, $badgeStart);
        $pdf->Cell($pdf->GetStringWidth($it['meals']) + 6, 5, ' ' . $it['meals'], 1, 0, 'C', true);
    }
    if ($it['accommodation']) {
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFillColor(23, 162, 184);
        $accX = $it['meals'] ? 18 + $pdf->GetStringWidth($it['meals']) + 6 : 14;
        $pdf->SetXY($accX, $badgeStart);
        $pdf->Cell($pdf->GetStringWidth($it['accommodation']) + 6, 5, ' ' . $it['accommodation'], 1, 0, 'C', true);
    }
    if ($it['meals'] || $it['accommodation']) $pdf->Ln(10);

    $pdf->Ln(3);
}

// Footer brand
$pdf->Ln(5);
$pdf->SetFont('Helvetica', 'I', 9);
$pdf->SetTextColor(150, 150, 150);
$pdf->Cell(0, 6, 'Generated by TourAndTravel — Your World of Joy', 0, 1, 'C');

// Output
$filename = 'tour-itinerary-' . $tour['slug'] . '.pdf';
$filename = substr(preg_replace('/[^a-zA-Z0-9._-]/', '_', $filename), 0, 90) . '.pdf';

// Output — web: download, CLI: write to stdout
if (php_sapi_name() === 'cli') {
    $pdf->Output('F', '/tmp/tour_itinerary_output.pdf');
    echo 'OK: /tmp/tour_itinerary_output.pdf (' . filesize('/tmp/tour_itinerary_output.pdf') . ' bytes)';
} else {
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    $pdf->Output('D', $filename);
}
exit;
