SET NAMES utf8mb4;
INSERT INTO translations (`key`, lang, value) VALUES
('AI AUTO (tulis 1 bahasa, auto translate)', 'en', 'AI AUTO (write in 1 language, auto-translate)'),
('AI AUTO (tulis 1 bahasa, auto translate)', 'id', 'AI AUTO (tulis 1 bahasa, auto translate)'),
('AI AUTO (tulis 1 bahasa, auto translate)', 'zh', 'AI自动（写1种语言，自动翻译）'),
('AI translate gagal', 'en', 'AI translation failed'),
('AI translate gagal', 'id', 'AI translate gagal'),
('AI translate gagal', 'zh', 'AI翻译失败'),
('Bahasa sumber (yang kamu tulis)', 'en', 'Source language (the one you write)'),
('Bahasa sumber (yang kamu tulis)', 'id', 'Bahasa sumber (yang kamu tulis)'),
('Bahasa sumber (yang kamu tulis)', 'zh', '源语言（您填写的语言）'),
('Bahasa sumber tidak valid', 'en', 'Invalid source language'),
('Bahasa sumber tidak valid', 'id', 'Bahasa sumber tidak valid'),
('Bahasa sumber tidak valid', 'zh', '源语言无效'),
('Isi dulu minimal 1 kolom dalam bahasa sumber.', 'en', 'Fill in at least 1 column in the source language first.'),
('Isi dulu minimal 1 kolom dalam bahasa sumber.', 'id', 'Isi dulu minimal 1 kolom dalam bahasa sumber.'),
('Isi dulu minimal 1 kolom dalam bahasa sumber.', 'zh', '请先用源语言至少填写1个栏目。'),
('kolom terisi otomatis — cek dengan pindah ke mode Manual.', 'en', 'columns auto-filled — switch to Manual mode to review.'),
('kolom terisi otomatis — cek dengan pindah ke mode Manual.', 'id', 'kolom terisi otomatis — cek dengan pindah ke mode Manual.'),
('kolom terisi otomatis — cek dengan pindah ke mode Manual.', 'zh', '个栏目已自动填写——切换到手动模式检查。'),
('Manual (isi 3 bahasa sendiri)', 'en', 'Manual (fill in 3 languages yourself)'),
('Manual (isi 3 bahasa sendiri)', 'id', 'Manual (isi 3 bahasa sendiri)'),
('Manual (isi 3 bahasa sendiri)', 'zh', '手动（自行填写3种语言）'),
('Menerjemahkan via AI...', 'en', 'Translating via AI...'),
('Menerjemahkan via AI...', 'id', 'Menerjemahkan via AI...'),
('Menerjemahkan via AI...', 'zh', 'AI翻译中……'),
('Mode Input:', 'en', 'Input Mode:'),
('Mode Input:', 'id', 'Mode Input:'),
('Mode Input:', 'zh', '输入模式：'),
('Refresh halaman untuk melihat hasil.', 'en', 'Refresh the page to see the result.'),
('Refresh halaman untuk melihat hasil.', 'id', 'Refresh halaman untuk melihat hasil.'),
('Refresh halaman untuk melihat hasil.', 'zh', '刷新页面查看结果。'),
('Terjemahkan Otomatis (pratinjau)', 'en', 'Auto-Translate (preview)'),
('Terjemahkan Otomatis (pratinjau)', 'id', 'Terjemahkan Otomatis (pratinjau)'),
('Terjemahkan Otomatis (pratinjau)', 'zh', '自动翻译（预览）'),
('Tulis Judul, Kategori & Deskripsi dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'en', 'Write Title, Category & Description in 1 language (see Content Language), click preview to check the result, then Save — any columns left empty are auto-translated by AI on save.'),
('Tulis Judul, Kategori & Deskripsi dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'id', 'Tulis Judul, Kategori & Deskripsi dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.'),
('Tulis Judul, Kategori & Deskripsi dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'zh', '用1种语言填写标题、分类和描述（见内容语言），点击预览查看结果，然后保存——保存时空白栏目将由AI自动翻译。'),
('Tulis semua kolom dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan. Itinerary, jadwal & galeri dilengkapi di halaman Edit.', 'en', 'Write all columns in 1 language (see Content Language), click preview to check the result, then Save — any columns left empty are auto-translated by AI on save. Itinerary, dates & gallery are completed on the Edit page.'),
('Tulis semua kolom dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan. Itinerary, jadwal & galeri dilengkapi di halaman Edit.', 'id', 'Tulis semua kolom dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan. Itinerary, jadwal & galeri dilengkapi di halaman Edit.'),
('Tulis semua kolom dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Simpan — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan. Itinerary, jadwal & galeri dilengkapi di halaman Edit.', 'zh', '用1种语言填写所有栏目（见内容语言），点击预览查看结果，然后保存——保存时空白栏目将由AI自动翻译。行程、日期和相册请在编辑页补充。'),
('Ubah teks dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Update — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'en', 'Edit the text in 1 language (see Content Language), click preview to check the result, then Update — any columns left empty are auto-translated by AI on save.'),
('Ubah teks dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Update — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'id', 'Ubah teks dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Update — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.'),
('Ubah teks dalam 1 bahasa (lihat Bahasa Konten), klik pratinjau untuk cek hasil, lalu Update — kolom yang masih kosong otomatis diterjemahkan AI saat disimpan.', 'zh', '用1种语言修改文本（见内容语言），点击预览查看结果，然后更新——保存时空白栏目将由AI自动翻译。')
ON DUPLICATE KEY UPDATE value = VALUES(value);
