-- ============================================================
-- migrate-price-calendar.sql — Fase 1 KEKURANGAN: kalender harga
-- Tabel price_calendar (item_type, item_id, date, price, slots, currency)
-- + seed 90 hari untuk 5 tour (id 61-65).
-- Idempotent: aman dijalankan berulang.
-- ============================================================

CREATE TABLE IF NOT EXISTS price_calendar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_type VARCHAR(20) NOT NULL DEFAULT 'tour',   -- tour|hotel|flight
    item_id INT NOT NULL,
    date DATE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    slots INT DEFAULT NULL,                          -- NULL = unlimited
    currency VARCHAR(5) NOT NULL DEFAULT 'IDR',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_item_date (item_type, item_id, date),
    INDEX idx_pc_lookup (item_type, item_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed 90 hari ke depan untuk 5 tour: harga dasar ± variasi weekend.
-- Idempotent via INSERT IGNORE (uniq_item_date).
INSERT IGNORE INTO price_calendar (item_type, item_id, date, price, slots, currency)
SELECT 'tour', t.id,
       CURDATE() + INTERVAL n.i - 1 DAY,
       ROUND(t.price * (CASE WHEN DAYOFWEEK(CURDATE() + INTERVAL n.i - 1 DAY) IN (1,7) THEN 1.15 ELSE 1.00 END), 2),
       NULL,
       t.price_currency
FROM tours t
JOIN (
    SELECT 1 AS i UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90
) n
WHERE t.id BETWEEN 61 AND 65;
