<?php
/**
 * Translate Migrate — seed terjemahan id/en ke tabel translations
 * Mapping manual dari scripts/out/missing_keys.txt
 * Run: php scripts/translate-migrate.php
 */

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/db.php';

$map = [
    'AC' => 'AC',
    'Admin' => 'Admin',
    'Ajak Teman, Dapatkan KlookCash!' => 'Invite Friends, Get KlookCash!',
    'Aksi' => 'Actions',
    'Aktivasi instan setelah pembayaran' => 'Instant activation after payment',
    'Alamat / terminal / hotel' => 'Address / terminal / hotel',
    'Alamat email Anda' => 'Your email address',
    'Anda booking sebagai tamu. Masuk akun untuk melacak booking.' => 'You are booking as a guest. Log in to track your booking.',
    'Anda dapat booking sebagai tamu.' => 'You can book as a guest.',
    'Asuransi perjalanan' => 'Travel insurance',
    'Atraksi' => 'Attractions',
    'Bagasi' => 'Baggage',
    'Bagikan link di bawah — Anda & teman dapat reward Rp50.000 saat teman berhasil daftar.' => 'Share the link below — you & your friend get Rp50.000 reward when they register.',
    'Bahan bakar' => 'Fuel',
    'Bangku reclining' => 'Reclining seat',
    'Bantuan' => 'Help',
    'Bantuan 24 jam' => '24-hour assistance',
    'Batal Gratis' => 'Free Cancellation',
    'Beli Sekarang' => 'Buy Now',
    'Belum ada item di collection ini.' => 'No items in this collection yet.',
    'Belum ada pertanyaan.' => 'No questions yet.',
    'Belum ada referral. Bagikan link Anda!' => 'No referrals yet. Share your link!',
    'Belum ada transaksi.' => 'No transactions yet.',
    'Berangkat' => 'Depart',
    'Berhasil Daftar' => 'Registered',
    'Berlangganan' => 'Subscribe',
    'Berlangganan newsletter kami untuk promo eksklusif & tips perjalanan.' => 'Subscribe to our newsletter for exclusive promos & travel tips.',
    'Best Seller' => 'Best Seller',
    'Bintang' => 'Stars',
    'Bintang Tertinggi' => 'Highest Rated',
    'Bonus' => 'Bonus',
    'Booking untuk dapat KlookCash' => 'Book to earn KlookCash',
    'Cakupan' => 'Coverage',
    'Coba: Batam → Singapore, atau ubah tanggal.' => 'Try: Batam → Singapore, or change the date.',
    'Collection Tidak Ditemukan' => 'Collection Not Found',
    'Collection tidak ditemukan' => 'Collection not found',
    'Colokan listrik' => 'Power outlet',
    'Contoh: Batam → Singapore, Johor → Batam.' => 'Example: Batam → Singapore, Johor → Batam.',
    'Daftar Referral' => 'Referral List',
    'Dapatkan Penawaran Terbaik' => 'Get the Best Deals',
    'Dari' => 'From',
    'Detail Produk' => 'Product Details',
    'Driver profesional' => 'Professional driver',
    'Earn' => 'Earn',
    'Email' => 'Email',
    'FAQ / Bantuan' => 'FAQ / Help',
    'Fasilitas' => 'Facilities',
    'Filter' => 'Filter',
    'Gunakan KlookCash' => 'Use KlookCash',
    'Gunakan untuk potongan booking berikutnya' => 'Use for discount on your next booking',
    'Harga Terendah' => 'Lowest Price',
    'Harga Termahal' => 'Highest Price',
    'Harga Termurah' => 'Cheapest',
    'Harga Tertinggi' => 'Highest Price',
    'Harga per Malam' => 'Price per Night',
    'Hemat' => 'Save',
    'Hotel' => 'Hotel',
    'Jadwal Ferry' => 'Ferry Schedule',
    'Jadwal keberangkatan pukul' => 'Departure at',
    'Jam Berangkat' => 'Departure Time',
    'Jam Penjemputan' => 'Pickup Time',
    'Jam penjemputan harus diisi' => 'Pickup time is required',
    'Jelajahi Tour' => 'Explore Tours',
    'Jumlah' => 'Quantity',
    'Jumlah Kursi' => 'Number of Seats',
    'Jumlah Penumpang' => 'Number of Passengers',
    'Jumlah Tiket' => 'Number of Tickets',
    'Jumlah kursi minimal 1' => 'Minimum 1 seat',
    'Jumlah minimal 1' => 'Minimum 1',
    'Jumlah penumpang minimal 1' => 'Minimum 1 passenger',
    'Jumlah tiket minimal 1' => 'Minimum 1 ticket',
    'Kapal' => 'Vessel',
    'Kategori' => 'Category',
    'Kembali ke Beranda' => 'Back to Home',
    'Kembali ke Katalog' => 'Back to Catalog',
    'Kereta' => 'Train',
    'Kereta Api' => 'Train',
    'Kereta Lain' => 'Other Trains',
    'Kereta Tidak Ditemukan' => 'Train Not Found',
    'Kereta tidak ditemukan' => 'Train not found',
    'Kode Promo (opsional)' => 'Promo Code (optional)',
    'Konfirmasi Instan' => 'Instant Confirmation',
    'Konfirmasi instan via WhatsApp' => 'Instant confirmation via WhatsApp',
    'Kota' => 'City',
    'Kuota' => 'Quota',
    'Lacak Booking' => 'Track Booking',
    'Login' => 'Login',
    'Login untuk Booking' => 'Login to Book',
    'Lokasi Penjemputan' => 'Pickup Location',
    'Lokasi penjemputan harus diisi' => 'Pickup location is required',
    'Maksimal' => 'Maximum',
    'Masa aktif' => 'Validity period',
    'Masih butuh bantuan?' => 'Still need help?',
    'Maskapai' => 'Airline',
    'Masuk / Daftar' => 'Login / Register',
    'Masukkan kota asal dan tujuan untuk mencari jadwal ferry.' => 'Enter departure and destination to search ferry schedules.',
    'Metode Pembayaran' => 'Payment Methods',
    'Nama' => 'Name',
    'Negara' => 'Country',
    'Nikmati perjalanan' => 'Enjoy your trip',
    'No. Penerbangan (opsional)' => 'Flight No. (optional)',
    'One Way' => 'One Way',
    'Pakai' => 'Use',
    'Pembayaran aman & terenkripsi' => 'Secure & encrypted payment',
    'Pencarian' => 'Search',
    'Pergi' => 'Depart',
    'Perusahaan' => 'Company',
    'Pesan Tiket' => 'Book Ticket',
    'Pesan Transfer' => 'Book Transfer',
    'Pramusaji' => 'Cabin attendant',
    'Produk Tidak Ditemukan' => 'Product Not Found',
    'Produk tidak ditemukan' => 'Product not found',
    'Pusat Bantuan' => 'Help Center',
    'Refund' => 'Refund',
    'Refundable' => 'Refundable',
    'Reward 5% dari total booking — bisa dipakai untuk booking berikutnya' => '5% reward from total booking — usable for your next booking',
    'Riwayat Transaksi' => 'Transaction History',
    'Round Trip' => 'Round Trip',
    'Saldo KlookCash' => 'KlookCash Balance',
    'Salin' => 'Copy',
    'Selimut' => 'Blanket',
    'Semua Bintang' => 'All Stars',
    'Semua Durasi' => 'All Durations',
    'Semua Harga' => 'All Prices',
    'Semua Kelas' => 'All Classes',
    'Semua Lokasi' => 'All Locations',
    'Semua Negara' => 'All Countries',
    'Semua Rating' => 'All Ratings',
    'Semua Tujuan' => 'All Destinations',
    'Sesampainya di pelabuhan, tunjukkan e-ticket ke petugas.' => 'Upon arrival at the port, show your e-ticket to the officer.',
    'Spend' => 'Spend',
    'Tamu' => 'Guests',
    'Tanggal' => 'Date',
    'Tanggal Kunjungan' => 'Visit Date',
    'Tanggal Penjemputan' => 'Pickup Date',
    'Tanggal Perjalanan' => 'Travel Date',
    'Tanggal Pulang' => 'Return Date',
    'Tanggal kunjungan harus diisi' => 'Visit date is required',
    'Tanggal penjemputan harus diisi' => 'Pickup date is required',
    'Tanggal perjalanan harus diisi' => 'Travel date is required',
    'Temukan jawaban atas pertanyaan yang sering diajukan' => 'Find answers to frequently asked questions',
    'Terapkan' => 'Apply',
    'Tercepat' => 'Fastest',
    'Termasuk' => 'Includes',
    'Tiba' => 'Arrive',
    'Tidak ada hotel ditemukan.' => 'No hotels found.',
    'Tidak ada jadwal ferry untuk rute/tanggal ini.' => 'No ferry schedule for this route/date.',
    'Tidak ada kereta ditemukan.' => 'No trains found.',
    'Tidak ada produk ditemukan.' => 'No products found.',
    'Tidak ada tiket ditemukan.' => 'No tickets found.',
    'Tidak ada transfer ditemukan.' => 'No transfers found.',
    'Tiket Lain di' => 'Other Tickets in',
    'Tiket Tempat Wisata' => 'Attraction Tickets',
    'Tiket Tidak Ditemukan' => 'Ticket Not Found',
    'Tiket tidak ditemukan' => 'Ticket not found',
    'Tipe' => 'Type',
    'Tipe Kendaraan' => 'Vehicle Type',
    'Tipe Mobil' => 'Car Type',
    'Toilet' => 'Toilet',
    'Total Referral' => 'Total Referrals',
    'Total Reward' => 'Total Reward',
    'Tour tidak ditemukan' => 'Tour not found',
    'Transfer' => 'Transfer',
    'Transfer Bandara' => 'Airport Transfer',
    'Transfer Lain' => 'Other Transfers',
    'Transfer Tidak Ditemukan' => 'Transfer Not Found',
    'Transfer tidak ditemukan' => 'Transfer not found',
    'Transit' => 'Transit',
    'Ulasan' => 'Reviews',
    'bagasi' => 'baggage',
    'dan tiba pukul' => 'and arrives at',
    'dengan' => 'with',
    'dengan estimasi perjalanan' => 'with an estimated travel time of',
    'eSIM' => 'eSIM',
    'eSIM & Connectivity' => 'eSIM & Connectivity',
    'hari' => 'days',
    'hotel ditemukan' => 'hotels found',
    'kabin' => 'cabin',
    'kelas' => 'class',
    'kendaraan' => 'vehicle',
    'kereta ditemukan' => 'trains found',
    'menuju' => 'to',
    'penumpang' => 'passengers',
    'per referral' => 'per referral',
    'produk ditemukan' => 'products found',
    'tiket' => 'ticket',
    'tiket ditemukan' => 'tickets found',
    'tour' => 'tour',
    'transfer ditemukan' => 'transfers found',
];

$ins = db()->prepare("INSERT INTO translations (`key`, lang, value) VALUES (?, 'id', ?) ON DUPLICATE KEY UPDATE value = VALUES(value)");
$insEn = db()->prepare("INSERT INTO translations (`key`, lang, value) VALUES (?, 'en', ?) ON DUPLICATE KEY UPDATE value = VALUES(value)");

$inserted = 0;
$updated = 0;
foreach ($map as $id => $en) {
    $ins->execute([$id, $id]);
    $insEn->execute([$id, $en]);
    $inserted++;
}

echo "Mapping keys processed: $inserted\n";
$cnt = db()->query("SELECT COUNT(*) FROM translations WHERE lang='en'")->fetchColumn();
echo "Total en rows now: $cnt\n";
$cntId = db()->query("SELECT COUNT(*) FROM translations WHERE lang='id'")->fetchColumn();
echo "Total id rows now: $cntId\n";
